language: java
install: mvn dependency:go-offline -B -V
before_script: sudo apt-get -y update && sudo apt-get -y install devscripts build-essential
script:
  - mvn clean cobertura:cobertura -Dtest=WatchDirTest#createdFileIsDetected -DfailIfNoTests=false
